Repository rcore-os/zCore, pull requests merged in 2020-06, with the labels that each got.

#53 Implement PCI related syscalls
  kernel-hal-bare/Cargo.toml
  kernel-hal-bare/src/arch/x86_64/acpi_table.rs
  kernel-hal-bare/src/arch/x86_64/interrupt.rs
  kernel-hal-bare/src/arch/x86_64/mod.rs
  kernel-hal/Cargo.toml
  kernel-hal/src/dummy.rs
  zCore/Makefile
  zircon-loader/src/lib.rs
  zircon-object/Cargo.toml
  zircon-object/src/debuglog.rs
  zircon-object/src/dev/interrupt/event_interrupt.rs
  zircon-object/src/dev/interrupt/mod.rs
  zircon-object/src/dev/interrupt/pci_interrupt.rs
  zircon-object/src/dev/iommu.rs
  zircon-object/src/dev/mod.rs
  zircon-object/src/dev/pci/bus.rs
  zircon-object/src/dev/pci/caps.rs
  zircon-object/src/dev/pci/config.rs
  zircon-object/src/dev/pci/mod.rs
  zircon-object/src/dev/pci/nodes.rs
  zircon-object/src/dev/pci/pio.rs
  zircon-object/src/object/handle.rs
  zircon-object/src/object/rights.rs
  zircon-object/src/vm/mod.rs
  zircon-object/src/vm/vmar.rs
  zircon-object/src/vm/vmo/paged.rs
  zircon-syscall/src/lib.rs
  zircon-syscall/src/pci.rs
  zircon-syscall/src/signal.rs
Labels: enhancement

#57 Fixes and workarounds about PCI on qemu
  kernel-hal-bare/src/arch/x86_64/interrupt.rs
  zircon-loader/src/lib.rs
  zircon-object/src/dev/pci/bus.rs
  zircon-object/src/dev/pci/caps.rs
  zircon-object/src/dev/pci/config.rs
  zircon-object/src/dev/pci/mod.rs
  zircon-object/src/dev/pci/nodes.rs
  zircon-syscall/src/object.rs
  zircon-syscall/src/pci.rs
Labels: bug

#58 Refactor PCI code
  kernel-hal-bare/src/arch/x86_64/interrupt.rs
  kernel-hal/src/dummy.rs
  kernel-hal/src/user.rs
  linux-object/src/error.rs
  zCore/rboot.conf
  zircon-loader/src/lib.rs
  zircon-object/src/dev/interrupt/mod.rs
  zircon-object/src/dev/interrupt/pci_interrupt.rs
  zircon-object/src/dev/pci/bus.rs
  zircon-object/src/dev/pci/caps.rs
  zircon-object/src/dev/pci/mod.rs
  zircon-object/src/dev/pci/nodes.rs
  zircon-object/src/dev/pci/pio.rs
  zircon-object/src/error.rs
  zircon-object/src/lib.rs
  zircon-syscall/src/lib.rs
  zircon-syscall/src/object.rs
  zircon-syscall/src/pci.rs
Labels: refactor

#59 Add auto test
  .github/workflows/main.yml
  README.md
  prebuilt/zircon/core-tests.zbi
  scripts/core-tests.py
  scripts/test-check-passed.txt
  scripts/testcases.txt
  zCore/Makefile
  zCore/rboot.conf
  zircon-loader/src/lib.rs
  zircon-syscall/Cargo.toml
  zircon-syscall/src/channel.rs
Labels: enhancement, good first issue

#60 Bring rCore back
  linux-loader/src/lib.rs
  linux-loader/src/main.rs
  linux-object/src/fs/device.rs
  linux-object/src/fs/mod.rs
  linux-object/src/loader/abi.rs
  linux-object/src/loader/mod.rs
  linux-object/src/process.rs
  linux-object/src/thread.rs
  linux-syscall/Cargo.toml
  linux-syscall/build.rs
  linux-syscall/src/consts.rs
  linux-syscall/src/file/dir.rs
  linux-syscall/src/file/fd.rs
  linux-syscall/src/file/file.rs
  linux-syscall/src/file/mod.rs
  linux-syscall/src/file/stat.rs
  linux-syscall/src/lib.rs
  linux-syscall/src/misc.rs
  linux-syscall/src/syscall.h.in
  linux-syscall/src/task.rs
  linux-syscall/src/vm.rs
  zCore/Cargo.toml
  zCore/Makefile
  zCore/src/main.rs
Labels: enhancement

#63 Fix contiguous vmo tests
  scripts/test-check-passed.txt
  scripts/testcases.txt
  zircon-object/src/vm/vmo/paged.rs
Labels: bug

#78 Add initial support for Zircon libos on ARM64 Linux
  .github/workflows/main.yml
  Cargo.toml
  README.md
  kernel-hal-bare/Cargo.toml
  kernel-hal-bare/src/arch/x86_64/mod.rs
  kernel-hal-bare/src/lib.rs
  kernel-hal-unix/Cargo.toml
  kernel-hal-unix/src/lib.rs
  kernel-hal-unix/src/trap.rs
  kernel-hal/Cargo.toml
  kernel-hal/src/dummy.rs
  prebuilt/zircon/arm64/bringup.zbi
  prebuilt/zircon/arm64/core-tests.zbi
  prebuilt/zircon/arm64/libzircon-libos.so
  prebuilt/zircon/arm64/libzircon.so
  prebuilt/zircon/arm64/userboot-libos.so
  prebuilt/zircon/arm64/userboot.so
  prebuilt/zircon/x64/bringup.zbi
  prebuilt/zircon/x64/core-tests.zbi
  prebuilt/zircon/x64/libzircon-libos.so
  prebuilt/zircon/x64/libzircon.so
  prebuilt/zircon/x64/userboot-libos.so
  prebuilt/zircon/x64/userboot.so
  scripts/zircon-libos.patch
  zCore/Cargo.toml
  zCore/Makefile
  zCore/src/main.rs
  zircon-loader/src/lib.rs
  zircon-loader/src/main.rs
  zircon-object/Cargo.toml
  zircon-object/src/task/thread.rs
  zircon-object/src/task/thread/thread_state.rs
  zircon-syscall/src/cprng.rs
  zircon-syscall/src/lib.rs
  zircon-syscall/src/object.rs
  zircon-syscall/src/pci.rs
Labels: enhancement

#79 Implement Linux fork
  linux-loader/src/lib.rs
  linux-object/src/process.rs
  linux-syscall/src/lib.rs
  linux-syscall/src/task.rs
  zircon-object/src/vm/vmar.rs
Labels: enhancement

#83 Update downcast-rs and lock its version
  linux-object/Cargo.toml
  zircon-object/Cargo.toml
Labels: bug

#86 Forbid clone of contiguous vmo
  scripts/test-check-passed.txt
  zircon-object/src/vm/vmo/paged.rs
Labels: bug

#88 Booting SMP on x86_64
  kernel-hal-bare/Cargo.toml
  kernel-hal-bare/src/arch/x86_64/mod.rs
  zCore/Makefile
  zCore/src/logging.rs
  zCore/src/main.rs
Labels: enhancement
