Repository rcore-os/zCore, pull requests merged in 2020-05, with the labels that each got.

#21 DDK: implement BTI, PMT, VMOContiguous
  kernel-hal-bare/src/arch/x86_64/mod.rs
  kernel-hal-bare/src/lib.rs
  kernel-hal/src/consts.rs
  kernel-hal/src/dummy.rs
  kernel-hal/src/lib.rs
  zCore/rboot.conf
  zCore/src/memory.rs
  zircon-loader/src/lib.rs
  zircon-object/src/dev/bti.rs
  zircon-object/src/dev/iommu.rs
  zircon-object/src/dev/mod.rs
  zircon-object/src/dev/pmt.rs
  zircon-object/src/lib.rs
  zircon-object/src/resource.rs
  zircon-object/src/task/process.rs
  zircon-object/src/vm/mod.rs
  zircon-object/src/vm/vmar.rs
  zircon-object/src/vm/vmo/mod.rs
  zircon-object/src/vm/vmo/paged.rs
  zircon-object/src/vm/vmo/physical.rs
  zircon-syscall/src/channel.rs
  zircon-syscall/src/ddk.rs
  zircon-syscall/src/debug.rs
  zircon-syscall/src/debuglog.rs
  zircon-syscall/src/lib.rs
  zircon-syscall/src/object.rs
  zircon-syscall/src/resource.rs
  zircon-syscall/src/time.rs
  zircon-syscall/src/vmo.rs
Labels: enhancement

#34 implement interrupt
  kernel-hal-bare/src/arch/x86_64/interrupt.rs
  kernel-hal-bare/src/arch/x86_64/mod.rs
  kernel-hal/src/dummy.rs
  zircon-object/src/dev/interrupt/event_interrupt.rs
  zircon-object/src/dev/interrupt/mod.rs
  zircon-object/src/dev/interrupt/virtual_interrupt.rs
  zircon-object/src/dev/mod.rs
  zircon-object/src/dev/resource.rs
  zircon-object/src/object/rights.rs
  zircon-object/src/object/signal.rs
  zircon-object/src/signal/port.rs
  zircon-object/src/signal/port_packet.rs
  zircon-object/src/task/thread.rs
  zircon-syscall/src/ddk.rs
  zircon-syscall/src/lib.rs
  zircon-syscall/src/object.rs
  zircon-syscall/src/port.rs
  zircon-syscall/src/time.rs
Labels: enhancement

#36 Improve code of Interrupt and Socket
  kernel-hal-bare/Cargo.toml
  kernel-hal-bare/src/arch/x86_64/interrupt.rs
  kernel-hal/src/dummy.rs
  zircon-object/src/dev/interrupt/event_interrupt.rs
  zircon-object/src/dev/interrupt/mod.rs
  zircon-object/src/dev/interrupt/virtual_interrupt.rs
  zircon-object/src/ipc/socket.rs
  zircon-object/src/signal/port.rs
  zircon-syscall/src/ddk.rs
  zircon-syscall/src/socket.rs
Labels: refactor

#37 fix some bug & make uart for irq4 fail
  zircon-object/src/dev/interrupt/event_interrupt.rs
  zircon-object/src/dev/interrupt/mod.rs
  zircon-object/src/dev/resource.rs
Labels: bug

#41 Socket datagram
  zircon-object/src/ipc/socket.rs
  zircon-object/src/object/signal.rs
  zircon-syscall/src/socket.rs
Labels: enhancement
