Repository rcore-os/zCore, pull requests merged in 2020-07, with the labels that each got.

#94 Simplify and improve DebugLog
  scripts/test-check-passed.txt
  zircon-object/src/debuglog.rs
  zircon-syscall/src/debuglog.rs
  zircon-syscall/src/lib.rs
Labels: enhancement

#96 Returns`ZxError::SHOULD_WAIT` when the queue is full in sys_port_queue
  scripts/test-check-passed.txt
  scripts/testcases.txt
  zircon-object/src/signal/port.rs
  zircon-object/src/signal/port_packet.rs
  zircon-syscall/src/port.rs
Labels: bug

#97 Fix memory leak in sys_vmo_replace_as_executable
  zircon-syscall/src/vmo.rs
Labels: bug

#93 Implement Stream object
  kernel-hal/src/lib.rs
  kernel-hal/src/user_io_vec.rs
  zircon-object/src/error.rs
  zircon-object/src/object/rights.rs
  zircon-object/src/vm/mod.rs
  zircon-object/src/vm/stream.rs
  zircon-object/src/vm/vmo/mod.rs
  zircon-object/src/vm/vmo/paged.rs
  zircon-object/src/vm/vmo/physical.rs
  zircon-object/src/vm/vmo/slice.rs
  zircon-syscall/src/lib.rs
  zircon-syscall/src/object.rs
  zircon-syscall/src/stream.rs
Labels: enhancement

#98 Refactor Stream
  .github/workflows/main.yml
  kernel-hal/src/lib.rs
  kernel-hal/src/user.rs
  kernel-hal/src/user_io_vec.rs
  linux-object/src/error.rs
  linux-syscall/src/file/file.rs
  linux-syscall/src/lib.rs
  linux-syscall/src/util.rs
  zircon-object/src/error.rs
  zircon-object/src/vm/stream.rs
  zircon-syscall/src/lib.rs
  zircon-syscall/src/stream.rs
Labels: refactor

#100 Improve docs for `zircon_object::object`
  zircon-object/src/object/handle.rs
  zircon-object/src/object/mod.rs
  zircon-object/src/object/rights.rs
  zircon-object/src/object/signal.rs
Labels: documentation

#101 Exception Channel, Part 1
  scripts/core-tests.py
  scripts/test-check-passed.txt
  scripts/testcases.txt
  zircon-loader/src/lib.rs
  zircon-object/src/object/handle.rs
  zircon-object/src/object/rights.rs
  zircon-object/src/task/exception.rs
  zircon-object/src/task/job.rs
  zircon-object/src/task/mod.rs
  zircon-object/src/task/process.rs
  zircon-object/src/task/thread.rs
  zircon-syscall/src/exception.rs
  zircon-syscall/src/lib.rs
  zircon-syscall/src/object.rs
Labels: enhancement

#110 Basic hypervisor support
  .github/workflows/main.yml
  kernel-hal-bare/src/arch/riscv.rs
  kernel-hal-bare/src/arch/x86_64/mod.rs
  kernel-hal-unix/src/lib.rs
  kernel-hal/src/dummy.rs
  rust-toolchain
  zCore/Cargo.toml
  zCore/Makefile
  zCore/src/memory.rs
  zircon-loader/src/kcounter.rs
  zircon-object/Cargo.toml
  zircon-object/src/hypervisor/guest.rs
  zircon-object/src/hypervisor/mod.rs
  zircon-object/src/hypervisor/vcpu.rs
  zircon-object/src/lib.rs
  zircon-object/src/object/mod.rs
  zircon-object/src/object/rights.rs
  zircon-object/src/signal/port.rs
  zircon-object/src/signal/port_packet.rs
  zircon-object/src/task/thread.rs
  zircon-object/src/vm/vmar.rs
  zircon-object/src/vm/vmo/mod.rs
  zircon-syscall/Cargo.toml
  zircon-syscall/src/hypervisor.rs
  zircon-syscall/src/lib.rs
Labels: enhancement

#112 Add some trivial tests to improve the coverage of `zircon_object::object`
  zircon-object/src/object/handle.rs
  zircon-object/src/object/mod.rs
  zircon-object/src/object/rights.rs
  zircon-object/src/object/signal.rs
  zircon-object/src/signal/port.rs
Labels: documentation

#113 Deploy docs on GitHub Actions
  .github/workflows/main.yml
Labels: enhancement

#115 Try to fix test `object::tests::wait_many`
  zircon-object/Cargo.toml
  zircon-object/src/object/mod.rs
Labels: bug

#116 Fix out-of-memory panic
  kernel-hal-bare/Cargo.toml
  zircon-syscall/src/system.rs
Labels: bug

#117 Add project template for building Zircon user programs
  .github/workflows/main.yml
  Cargo.toml
  README.md
  prebuilt/zircon/x64/Scrt1.o
  prebuilt/zircon/x64/libc.so
  prebuilt/zircon/x64/libfdio.so
  prebuilt/zircon/x64/libunwind.so
  prebuilt/zircon/x64/zbi-linux
  prebuilt/zircon/x64/zbi-macos
  zCore/Makefile
  zircon-user/.cargo/config
  zircon-user/Cargo.toml
  zircon-user/Makefile
  zircon-user/src/bin/hello.rs
Labels: enhancement
