Repository rcore-os/zCore, pull requests merged in 2020-08, with the labels that each got.

#125 Improve docs for `linux-syscall` and fix "uname" command
  linux-syscall/src/file/dir.rs
  linux-syscall/src/file/fd.rs
  linux-syscall/src/file/file.rs
  linux-syscall/src/file/mod.rs
  linux-syscall/src/file/stat.rs
  linux-syscall/src/lib.rs
  linux-syscall/src/misc.rs
  linux-syscall/src/task.rs
  linux-syscall/src/time.rs
  linux-syscall/src/vm.rs
Labels: documentation

#132 Add simple pipe syscall and unit test method for linux syscall
  Makefile
  linux-loader/src/main.rs
  linux-object/src/fs/file.rs
  linux-object/src/fs/mod.rs
  linux-object/src/fs/pipe.rs
  linux-syscall/src/file/fd.rs
  linux-syscall/src/lib.rs
  linux-syscall/test/testpipe1.c
  linux-syscall/test/testpipe2.c
Labels: enhancement

#120 Improve docs and tests for `zircon_object::signal`
  zircon-object/src/dev/interrupt/mod.rs
  zircon-object/src/signal/event.rs
  zircon-object/src/signal/eventpair.rs
  zircon-object/src/signal/futex.rs
  zircon-object/src/signal/mod.rs
  zircon-object/src/signal/port.rs
  zircon-object/src/signal/port_packet.rs
  zircon-object/src/signal/timer.rs
  zircon-syscall/src/port.rs
Labels: documentation

#123 Improve docs and tests for `zircon_object::ipc`
  zircon-object/src/ipc/channel.rs
  zircon-object/src/ipc/fifo.rs
  zircon-object/src/ipc/mod.rs
  zircon-object/src/ipc/socket.rs
  zircon-syscall/src/fifo.rs
  zircon-syscall/src/socket.rs
Labels: documentation

#135 Add more time syscalls and fix `touch` command in busybox
  linux-loader/src/main.rs
  linux-object/Cargo.toml
  linux-object/src/fs/fcntl.rs
  linux-object/src/fs/mod.rs
  linux-syscall/Cargo.toml
  linux-syscall/src/file/file.rs
  linux-syscall/src/lib.rs
  linux-syscall/src/time.rs
  linux-syscall/test/testpipe1.c
  linux-syscall/test/testpipe2.c
  linux-syscall/test/testtime.c
Labels: enhancement

#131 add some syscalls and add stdin
  linux-loader/Cargo.toml
  linux-object/Cargo.toml
  linux-object/src/error.rs
  linux-object/src/fs/file.rs
  linux-object/src/fs/mod.rs
  linux-object/src/fs/stdio.rs
  linux-object/src/process.rs
  linux-syscall/Cargo.toml
  linux-syscall/src/file/poll.rs
  linux-syscall/src/lib.rs
  linux-syscall/src/misc.rs
  linux-syscall/src/task.rs
  zCore/Cargo.toml
  zCore/Makefile
  zCore/gdbinit
Labels: enhancement

#108 Exception channel, part 2
  kernel-hal-bare/Cargo.toml
  kernel-hal-unix/Cargo.toml
  kernel-hal/Cargo.toml
  linux-loader/src/lib.rs
  scripts/test-check-passed.txt
  scripts/testcases.txt
  zCore/Cargo.toml
  zircon-loader/src/lib.rs
  zircon-object/src/task/exception.rs
  zircon-object/src/task/job.rs
  zircon-object/src/task/mod.rs
  zircon-object/src/task/process.rs
  zircon-object/src/task/thread.rs
  zircon-syscall/src/exception.rs
  zircon-syscall/src/lib.rs
  zircon-syscall/src/object.rs
  zircon-syscall/src/task.rs
Labels: enhancement

#141 Preliminary code comments have been added for Zircon-syscalls
  zircon-syscall/src/channel.rs
  zircon-syscall/src/cprng.rs
  zircon-syscall/src/ddk.rs
  zircon-syscall/src/debug.rs
  zircon-syscall/src/debuglog.rs
  zircon-syscall/src/exception.rs
  zircon-syscall/src/fifo.rs
  zircon-syscall/src/futex.rs
  zircon-syscall/src/handle.rs
  zircon-syscall/src/hypervisor.rs
  zircon-syscall/src/object.rs
  zircon-syscall/src/port.rs
  zircon-syscall/src/resource.rs
  zircon-syscall/src/signal.rs
  zircon-syscall/src/socket.rs
  zircon-syscall/src/stream.rs
  zircon-syscall/src/system.rs
  zircon-syscall/src/task.rs
  zircon-syscall/src/time.rs
  zircon-syscall/src/vmar.rs
  zircon-syscall/src/vmo.rs
Labels: documentation

#142 Improve doc in `linux-object` and migrate some simple syscalls
  linux-loader/src/main.rs
  linux-object/src/error.rs
  linux-object/src/fs/device.rs
  linux-object/src/fs/fcntl.rs
  linux-object/src/fs/file.rs
  linux-object/src/fs/mod.rs
  linux-object/src/fs/pseudo.rs
  linux-object/src/fs/random.rs
  linux-object/src/fs/stdio.rs
  linux-object/src/lib.rs
  linux-object/src/loader/abi.rs
  linux-object/src/loader/mod.rs
  linux-object/src/process.rs
  linux-object/src/thread.rs
  linux-syscall/src/file/fd.rs
  linux-syscall/src/file/poll.rs
  linux-syscall/src/lib.rs
  linux-syscall/src/misc.rs
  linux-syscall/src/task.rs
  linux-syscall/test/testpipe1.c
  linux-syscall/test/testrandom.c
Labels: documentation, enhancement

#139 Improve docs and tests for `zircon_object::task`
  zircon-object/src/signal/timer.rs
  zircon-object/src/task/exception.rs
  zircon-object/src/task/job.rs
  zircon-object/src/task/job_policy.rs
  zircon-object/src/task/mod.rs
  zircon-object/src/task/process.rs
  zircon-object/src/task/suspend_token.rs
  zircon-object/src/task/thread.rs
  zircon-object/src/task/thread/thread_state.rs
Labels: documentation

#145 Refactor exception
  zircon-loader/src/lib.rs
  zircon-object/src/hypervisor/vcpu.rs
  zircon-object/src/signal/futex.rs
  zircon-object/src/task/exception.rs
  zircon-object/src/task/job.rs
  zircon-object/src/task/mod.rs
  zircon-object/src/task/process.rs
  zircon-object/src/task/thread.rs
  zircon-syscall/src/channel.rs
  zircon-syscall/src/ddk.rs
  zircon-syscall/src/exception.rs
  zircon-syscall/src/futex.rs
  zircon-syscall/src/lib.rs
  zircon-syscall/src/object.rs
  zircon-syscall/src/port.rs
  zircon-syscall/src/task.rs
  zircon-syscall/src/time.rs
Labels: refactor

#143 Update stdin with EventBus
  kernel-hal-bare/src/arch/x86_64/mod.rs
  kernel-hal-unix/src/lib.rs
  kernel-hal/src/dummy.rs
  kernel-hal/src/future.rs
  linux-loader/src/main.rs
  linux-object/src/fs/file.rs
  linux-object/src/fs/mod.rs
  linux-object/src/fs/stdio.rs
  linux-object/src/lib.rs
  linux-object/src/sync/event_bus.rs
  linux-object/src/sync/mod.rs
  linux-syscall/src/file/file.rs
  linux-syscall/src/lib.rs
  linux-syscall/src/vm.rs
  zCore/src/main.rs
Labels: enhancement

#147 Refactor thread
  linux-loader/src/lib.rs
  linux-object/src/thread.rs
  linux-syscall/src/lib.rs
  linux-syscall/src/task.rs
  zircon-loader/src/lib.rs
  zircon-object/src/hypervisor/guest.rs
  zircon-object/src/hypervisor/mod.rs
  zircon-object/src/signal/futex.rs
  zircon-object/src/task/exception.rs
  zircon-object/src/task/job.rs
  zircon-object/src/task/process.rs
  zircon-object/src/task/suspend_token.rs
  zircon-object/src/task/thread.rs
  zircon-syscall/src/futex.rs
  zircon-syscall/src/hypervisor.rs
  zircon-syscall/src/lib.rs
  zircon-syscall/src/task.rs
Labels: refactor

#150 Fix problem of blocking in sys_wait4
  linux-object/src/process.rs
Labels: bug

#151 Add libc-test to CI
  .github/workflows/main.yml
  Makefile
  README.md
  linux-loader/src/main.rs
  scripts/core-tests.py
  scripts/libc-tests.py
  scripts/linux/test-allow-failed.txt
  scripts/zircon/test-check-passed.txt
  scripts/zircon/testcases.txt
  zircon-object/src/task/process.rs
Labels: enhancement

#154 Fix Zircon console configuration
  zCore/rboot.conf
Labels: bug

#155 Add some syscalls of signal
  linux-object/Cargo.toml
  linux-object/src/lib.rs
  linux-object/src/process.rs
  linux-object/src/signal/action.rs
  linux-object/src/signal/mod.rs
  linux-object/src/thread.rs
  linux-syscall/Cargo.toml
  linux-syscall/src/lib.rs
  linux-syscall/src/signal.rs
Labels: enhancement

#163 Improve docs for `zircon_object::hypervisor`
  .github/workflows/main.yml
  zircon-object/src/hypervisor/guest.rs
  zircon-object/src/hypervisor/mod.rs
  zircon-object/src/hypervisor/vcpu.rs
  zircon-object/src/lib.rs
Labels: documentation

#166 add missing docs for `zircon_object::dev`
  zircon-object/src/dev/bti.rs
  zircon-object/src/dev/interrupt/mod.rs
  zircon-object/src/dev/iommu.rs
  zircon-object/src/dev/mod.rs
  zircon-object/src/dev/pci/bus.rs
  zircon-object/src/dev/pci/caps.rs
  zircon-object/src/dev/pci/mod.rs
  zircon-object/src/dev/pci/nodes.rs
  zircon-object/src/dev/pci/pci_init_args.rs
  zircon-object/src/dev/pci/pio.rs
  zircon-object/src/dev/pmt.rs
  zircon-object/src/dev/resource.rs
  zircon-syscall/src/pci.rs
Labels: documentation
